version: '3.8'

name: ms-order

services:
  # 1. PostgreSQL (Order Database)
  postgres:
    image: postgres:15-alpine
    container_name: order_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_DB: order_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ms-order-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: order_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: order_user      # Dəyişdirildi
      RABBITMQ_DEFAULT_PASS: order_password  # Dəyişdirildi
    networks:
      - ms-order-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  # 3. Redis (Cache)
  redis:
    image: redis:7-alpine
    container_name: order_redis
    ports:
      - "6379:6379"
    networks:
      - ms-order-network

  # 4. Zipkin (Tracing)
#  zipkin:
#    image: openzipkin/zipkin
#    container_name: order_zipkin
#    ports:
#      - "9411:9411"
#    networks:
#      - ms-order-network

  # --- YOUR APP SERVICE ---
  
  # 5. Order Service (Java App)
  order-service:
    build: .
    container_name: order_service_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Database Connection
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_db
      - SPRING_DATASOURCE_USERNAME=order_user
      - SPRING_DATASOURCE_PASSWORD=order_password
      # RabbitMQ Connection
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=order_user
      - SPRING_RABBITMQ_PASSWORD=order_password
      # Redis Connection
      - SPRING_DATA_REDIS_HOST=redis
      # Zipkin Connection
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ms-order-network

networks:
  ms-order-network:
    driver: bridge

volumes:
  postgres_data: